import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '@/components/shared/NavBar'
import HeroSection from '@/components/homePage/HeroSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
          <NavBar/>
          <HeroSection/>
          description : Arthur Fleck, un comédien affligé par des troubles mentaux, se voit mis de côté par la société. Samorce ensuite une descente aux , 
    rating : 5 , 
      </main>
    </>
  )
}
